### PR TITLE
Remove licence

### PR DESCRIPTION
**Pull request by tobyweston**
Includes removal of licence preamble in source files and the LICENCE definition file.

**Note**. We retain copyright inherently. See https://www.gov.uk/copyright

So regardless of the statement `copyright (c) 2019 bob and dave`, the authors Bob and Dave would retain copyright. The Apache licence we used included the copyright statement in the source preamble and in removing it, we haven't lost that right. Copyright is legally unrelated to licensing (terms).

### CODE REVIEW

**Comment by lithgow** [comment]
Cool. I checked out the Berne Convention too and lots of countries are party to it.

Without the license would it be clear to people whether they can reuse and modify the work (without attribution)?

**Comment by tobyweston** [comment]
Not sure. No? We need to make it clear but this isn’t just about attribution.

The more I think about it, the more we need a license imo. CC-BY-SA OR CC-BY to protect us as much as attribution. I think this is non negotiable as the OSS community would attest to (having given birth to these types of licenses).

If any employer has an issue with this, it’s going to be blocker in my view. So glad we’re looking at options and #7 is reopened. This PR is half the story as Apache was prob inappropriate or at least a unilateral decision on my part and we should get consensus about what to do next.

**Comment by lithgow** [comment]
Yeah, I was mentioning attribution as I was imagining your average Joe looking at it, and wondering whether they could reuse it, and if so whether they'd have to attribute. Without a license they may not know, so may make honest mistakes.

Clearly we want to cover ourselves for dishonest usage too, and also cover ourselves against warranty, etc, so I agree we need to land on one. 

I think for this kind of material, share-alike is legit, no? Or do we want to allow people to build on it and redistribute for profit?

**Comment by tobyweston** [comment]
I feel like CC is the best choice then just agree on how restrictive.

I like the hardline approach or not allowing anyone to profit commercially for it (including ourselves).

**Comment by lithgow** [comment]
Does CC achieve that? CC-BY-SA permits commercial use.

**Comment by tobyweston** [comment]
I'm cancelling this PR as after discussion, there doesn't seem to be a reason to remove the Apache license

**Pull request closed without merging**
